title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" 

collections:
  anime:
    permalink: "/:collection/:title"
    output: true
  video:
    permalink: "/:collection/:categories/:title"
    output: true
defaults:
- scope:
    path: _anime
    type: anime
  values:
    layout: anime
- scope:
    path: _video
    type: video
  values:
    layout: video

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

pagination:
  enabled: true
  per_page: 8
  offset: 0
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

include: ['.htaccess']

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
