title: Flixmu TV
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://flixmu.com" 

collections:
  anime:
    permalink: "/:collection/:title"
    output: true
  video:
    permalink: "/:collection/:categories/:title"
    output: true
  article:
    permalink: "/:collection/:title"
    output: true
defaults:
- scope:
    path: _anime
    type: anime
  values:
    layout: anime
- scope:
    path: _video
    type: video
  values:
    layout: video
- scope:
    path: _article
    type: article
  values:
    layout: article

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-remote-include
  - jekyll-last-modified-at
  - jekyll-timeago
  - jekyll-last-modified-at

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

pagination:
  enabled: true

jekyll_timeago:
  depth: 1 # Level of detail
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: ''
  prefix_future: 'in'
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'

feed:
  collections:
    - video

kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext

sass:
  style: compressed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
